name: Build Next.js web application

on:
  push:
    branches: [ "main" ]

# needed so the workflow can create a Release
permissions:
  contents: write

jobs:
  build-project:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Debug build outputs
        run: |
          echo "Root:" && ls -la
          echo ".next:" && (ls -la .next || true)
          echo "out:" && (ls -la out || true)

      # Upload .next (SSR build)
      - name: Upload .next artifact (if present)
        if: ${{ hashFiles('.next/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next

      # Upload out (static export)
      - name: Upload out artifact (if present)
        if: ${{ hashFiles('out/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: next-export
          path: out

  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      # download the static export produced by build (adjust to next-build if you prefer SSR)
      - name: Download static export (out/)
        uses: actions/download-artifact@v4
        with:
          name: next-export            # must match the upload-artifact "name"
          path: site

      - name: Display structure of downloaded files
        run: ls -R site

      # zip the downloaded site into a single file
      - name: Create ZIP
        run: |
          cd site
          zip -r ../site-out-${{ github.run_number }}.zip .
          cd ..

      # create a GitHub Release and attach the ZIP
      - name: Create GitHub Release with asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: Release ${{ github.run_number }}
          files: site-out-${{ github.run_number }}.zip
